name: Run Examples
on: [workflow_dispatch, push]

jobs:
  run-examples:
    runs-on: ubuntu-latest
    env:
      ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
      TOKEN: ${{ inputs.token || '0xe3a7766d0361f50a3dd038c967479673b75f8b34' }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run price-quoter
        env:
          RPC_URL: https://base-mainnet.g.alchemy.com/v2/${{ env.ALCHEMY_API_KEY }}
        run:
          pnpx tsx examples/price-quoter.ts

      - name: Run static auction v2
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          RPC_URL: https://base-mainnet.g.alchemy.com/v2/${{ env.ALCHEMY_API_KEY }}
        run:
          pnpx tsx examples/static-auction-v2.ts

      - name: Run static auction v4
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          RPC_URL: https://base-mainnet.g.alchemy.com/v2/${{ env.ALCHEMY_API_KEY }}
          BENEFICIARY_1: "0x1234567890123456789012345678901234567890"
          BENEFICIARY_2: "0x1234567890123456789012345678901234567891"
        run:
          pnpx tsx examples/static-auction-v4.ts

      - name: Run dynamic auction v4
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          RPC_URL: https://base-mainnet.g.alchemy.com/v2/${{ env.ALCHEMY_API_KEY }}
        run:
          pnpx tsx examples/dynamic-auction-v4.ts
